# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wSgxcnxRF167R_LOBqOq_qai6hkhDTf4
"""

#import library dan data
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston

rumah=load_boston()
print(rumah)

#ubah ke pandas dataframe
df_x=pd.DataFrame(rumah.data, columns=rumah.feature_names)
df_y=pd.DataFrame(rumah.target)

#cari statistik dari data
df_x.describe()

#inisiasi model linearnya
reg = LinearRegression()

#buat train data(di split)
x_test, x_train, y_test, y_train=train_test_split(df_x,df_y,test_size=0.33,random_state=42)

#fit datanya
reg.fit(x_train,y_train)

#print koefisien dari feature
print(reg.coef_)

#print prediksi
y_pred=reg.predict(x_test)
print(y_pred)

print(y_test)

#cek performa pakai MSE(mean squared error)
print(np.mean((y_pred-y_test)**2))

from sklearn.metrics import mean_squared_error

print(mean_squared_error(y_test,y_pred))

print(reg.score(x_test,y_test))